language: csharp
solution: Library.sln
mono: none
dist: xenial
dotnet: 5.0.202
install:
  - nuget restore Library.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Debug Library.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./Library.Test/bin/Debug/netcoreapp3.1/testhost.dll