language: csharp
solution: Library.sln
mono: none
dist: xenial
dotnet: 5.0.202
before_install:
  - dotnet restore
script:
 - dotnet build CIDemo.sln -c Debug
 - dotnet test -c Debug --no-build Library.Test/Library.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover