language: csharp
solution: Library.sln
mono: none
dist: xenial
dotnet: 5.0.202
install:
  - powershell -c "Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine"
  - powershell -c "Import-Module PackageManagement; Install-PackageProvider Nuget"
  - powershell -c "Import-Module PackageManagement; Register-PackageSource -Name NuGetOrg -Location https://www.nuget.org/api/v2 -ProviderName NuGet"
  - powershell -c "Import-Module PackageManagement; Install-Package -Source NuGetOrg -Name NuGet.CommandLine -Force -ExcludeVersion -Destination C:\tools"
  - nuget restore Library.Test/Library.Test.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - dotnet restore
  - msbuild /p:Configuration=Debug Library.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./Library.Test/bin/Debug/netcoreapp3.1/testhost.dll