language: csharp
solution: Library.sln
mono: none
dist: xenial
dotnet: 3.1.408
before_install:
  - dotnet restore
script:
 - dotnet build Library.sln -c Debug
 - dotnet test -c Debug --no-build Library.Test/Library.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover