language: csharp
solution: Library.sln
mono: none
dist: xenial
dotnet: 3.1.408
notifications:
  email:
    recipients:
      - markoosha98@gmail.com
      - mah9@tpu.ru
    on_success: change
    on_failure: always
before_install:
  - dotnet restore
script:
 - dotnet build Library.sln -c Debug
 - dotnet test -c Debug --no-build Library.Test/Library.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover